# Generated by Django 5.1.1 on 2024-12-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, null=True)),
                ('ar_no', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(choices=[('20CY', '20CY'), ('21MY', '21MY'), ('CT1', 'CT1'), ('CT2', 'CT2'), ('CT3', 'CT3'), ('CT4', 'CT4'), ('OT', 'OT'), ('PNT', 'PNT'), ('PZT', 'PZT')], max_length=5)),
                ('ar_category', models.CharField(max_length=255)),
                ('abnormality', models.CharField(max_length=120)),
                ('nature_of_abnormality', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('affected_item', models.CharField(blank=True, max_length=500, null=True)),
                ('level', models.CharField(choices=[('One', 1), ('Two', 2)], default='One', max_length=3)),
                ('created', models.CharField(max_length=10)),
                ('detection_process', models.CharField(max_length=500)),
                ('function', models.CharField(max_length=10)),
                ('incharge', models.CharField(max_length=255)),
                ('self_resolve_for_car', models.CharField(choices=[('FOR CAR', 'FOR CAR'), ('SELF RESOLVE', 'SELF RESOLVE')], max_length=12)),
                ('status', models.CharField(choices=[('CAR CREATION', 'CAR CREATION'), ('UNDER REVIEW', 'UNDER REVIEW'), ('APPROVED', 'APPROVED'), ('IMPLEMENTATION', 'IMPLEMENTATION'), ('VALIDATION', 'VALIDATION'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=14)),
                ('countermeasure', models.CharField(blank=True, max_length=255, null=True)),
                ('fanout', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
