# Generated by Django 5.1.3 on 2024-12-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('ar_num', models.IntegerField(default=0)),
                ('area', models.CharField(choices=[('20CY', 1), ('21MY', 2), ('CT1', 3), ('CT2', 4), ('CT3', 5), ('CT4', 6), ('OT', 7), ('PNT', 8), ('PZT', 9)], max_length=5)),
                ('ar_category', models.CharField(max_length=255)),
                ('nature_of_abnormality', models.CharField(max_length=400)),
                ('affected_item', models.CharField(max_length=500)),
                ('level', models.CharField(choices=[('One', 1), ('Two', 2)], default='One', max_length=3)),
                ('created', models.CharField(max_length=10)),
                ('detection_process', models.CharField(max_length=500)),
                ('function', models.CharField(max_length=3)),
                ('incharge', models.CharField(max_length=255)),
                ('self_resolve_for_car', models.CharField(choices=[('FOR CAR', 1), ('SELF RESOLVE', 2)], max_length=12)),
                ('carnumber', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 1), ('FOR CREATION', 2)], max_length=12)),
                ('countermeasure', models.CharField(max_length=255)),
                ('fanout', models.BooleanField(default=True)),
                ('remarks', models.CharField(max_length=255)),
                ('month', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
