# Generated by Django 5.1.3 on 2024-12-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_category_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ar_num',
        ),
        migrations.RemoveField(
            model_name='category',
            name='carnumber',
        ),
        migrations.AlterField(
            model_name='category',
            name='area',
            field=models.CharField(choices=[(1, '20CY'), (2, '21MY'), (3, 'CT1'), (4, 'CT2'), (5, 'CT3'), (6, 'CT4'), (7, 'OT'), (8, 'PNT'), (9, 'PZT')], max_length=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='self_resolve_for_car',
            field=models.CharField(choices=[(1, 'FOR CAR'), (2, 'SELF RESOLVE')], max_length=12),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[(1, 'OPEN'), (2, 'FOR CREATION')], max_length=12),
        ),
    ]
