# Generated by Django 5.1.1 on 2024-12-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='link',
        ),
        migrations.AlterField(
            model_name='category',
            name='affected_item',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='countermeasure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='nature_of_abnormality',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
