# Generated by Django 5.1.1 on 2024-12-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_category_link_alter_category_affected_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('CAR CREATION', 'CAR CREATION'), ('UNDER REVIEW', 'UNDER REVIEW'), ('APPROVED', 'APPROVED'), ('IMPLEMENTATION', 'IMPLEMENTATION'), ('VALIDATION', 'VALIDATION'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=14),
        ),
    ]
