# Generated by Django 5.1.1 on 2024-12-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ar_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='function',
            field=models.CharField(max_length=10),
        ),
    ]
